import React from 'react'
import { useParams, useNavigate } from 'react-router-dom';
import "../assets/Style.css"
import { Link } from 'react-router-dom';
import images from "../assets/images/Iphone13.jpg"
import Shirt from "../assets/images/Iphone14.jpg"
import Watch from "../assets/images/iphonePlus.jpg"
import Phone from "../assets/images/Iphone16.webp";
import Shoes from "../assets/images/Samsung2.webp";
import Samsung1 from "../assets/images/Samsung1.webp"
import Samsung3 from "../assets/images/Samsung3.webp"
import Samsung4 from "../assets/images/Samsung4.webp"
import Maytinh1 from "../assets/images/Maytinh1.webp"
import Maytinh2 from "../assets/images/Maytinh2.webp"
import Maytinh3 from "../assets/images/Maytinh3.webp"
import Maytinh4 from "../assets/images/Maytinh4.webp"
import Maytinh5 from "../assets/images/Maytinh5.webp"
import Maytinh6 from "../assets/images/Maytinh6.webp"
import Maytinh7 from "../assets/images/Maytinh7.webp"
import Maytinh8 from "../assets/images/Maytinh8.webp"
import Tainghe1 from "../Product/images/Tainghe1.webp"
import Tainghe2 from "../Product/images/Tainghe2.webp"
import Tainghe3 from "../Product/images/Tainghe3.webp"
import Tainghe4 from "../Product/images/Tainghe4.webp"
import Tainghe5 from "../Product/images/Tainghe5.webp"
import Tainghe6 from "../Product/images/Tainghe6.webp"
import Tainghe7 from "../Product/images/Tainghe7.webp"
import Tainghe8 from "../Product/images/Tainghe8.webp"
import Watch1 from '../Watch/images/Watch1.webp'
import Watch2 from '../Watch/images/Watch2.webp'
import Watch3 from '../Watch/images/Watch3.webp'
import Watch4 from '../Watch/images/Watch4.webp'
import Watch5 from '../Watch/images/Watch5.webp'
import Watch6 from '../Watch/images/Watch6.webp'
import Watch7 from '../Watch/images/Watch7.webp'
import Watch8 from '../Watch/images/Watch8.webp'
import sale1 from '../assets/images/sale1.webp'
import sale2 from '../assets/images/sale2.webp'
import sale3 from '../assets/images/sale3.webp'
import sale4 from '../assets/images/sale4.webp'
import sale5 from '../assets/images/sale5.webp'
import sale6 from '../assets/images/sale6.webp'
import sale7 from '../assets/images/sale7.webp'
import Ipad1 from '../Ipad/images/Ipad1.webp'
import Ipad2 from '../Ipad/images/Ipad2.webp'
import Ipad3 from '../Ipad/images/Ipad3.webp'
import Ipad4 from '../Ipad/images/Ipad4.webp'
import Ipad5 from '../Ipad/images/Ipad5.webp'
import Ipad6 from '../Ipad/images/Ipad6.webp'
import Ipad7 from '../Ipad/images/Ipad7.webp'
import Ipad8 from '../Ipad/images/Ipad8.webp'
import Laptop1 from "../Laptop/images/Laptop1.webp"
import Laptop2 from "../Laptop/images/Laptop2.webp"
import Laptop3 from "../Laptop/images/Laptop3.webp"
import Laptop4 from "../Laptop/images/Laptop4.webp"
import Laptop5 from "../Laptop/images/Laptop5.webp"
import Laptop6 from "../Laptop/images/Laptop6.webp"
import Laptop7 from "../Laptop/images/Laptop7.webp"
import Laptop8 from "../Laptop/images/Laptop8.webp"
import Mouse1 from "../Mouse/images/chuot1.jpg"
import Mouse2 from "../Mouse/images/chuot2.jpg"
import Mouse3 from "../Mouse/images/chuot3.jpeg"
import Mouse4 from "../Mouse/images/chuot4.jpg"
import Mouse5 from "../Mouse/images/chuot5.jpg"
import Mouse6 from "../Mouse/images/chuot6.jpg"
import Mouse7 from "../Mouse/images/chuot7.jpg"
import Mouse8 from "../Mouse/images/chuot8.jpg"
import KeyBoard1 from "../KeyBoard/images/bp1.jpeg"
import KeyBoard2 from "../KeyBoard/images/bp2.jpeg"
import KeyBoard3 from "../KeyBoard/images/bp3.jpeg"
import KeyBoard4 from "../KeyBoard/images/bp4.jpg"
import KeyBoard5 from "../KeyBoard/images/bp5.jpg"
import KeyBoard6 from "../KeyBoard/images/bp6.jpg"
import KeyBoard7 from "../KeyBoard/images/bp7.jpg"
import KeyBoard8 from "../KeyBoard/images/bp8.jpg"
import Footer from '../footer/Footer';



const products= [
    { id: 1,  name: 'Iphone 13',price: 3000, describe:'Smart Phone' , image:images,quantity: 1,description: 'A smartphone with latest features'},
    { id: 2,  name: 'Iphone 14',price: 3000, describe:'Smart Phone', image:Shirt, quantity: 1,description: 'The Premium Round Neck Shirt from Craft Clothing is a testament to comfort and quality' },
    { id: 3,  name: 'Iphone 12',price: 3000, describe:'Smart Phone', image:Watch, quantity: 1,description: 'A Watch with latest features' },
    { id: 4,  name: 'Iphone 16',price: 3000, describe:'Smart Phone', image:Phone, quantity: 1,description: 'A Phone with latest features'},
    { id: 5,  name: 'Samsung Galaxy S24',price: 3000, describe: 'Smart Phone', category: 'Clothing', quantity: 1, image: Shoes, description: ' phiên bản 512GB được trang bị con chip Exynos 2400 kết hợp cùng dung lượng RAM 12GB cho hiệu năng đáng kinh ngạc. Cụm camera với cảm biến chính 50MP đảm bảo mang tới những bức ảnh sống động và khả năng quay video Super HDR đỉnh cao. Màn hình Dynamic AMOLED 2X cùng độ phân giải Quad-HD+ với độ sáng 2.600 nit hỗ trợ mang lại khả năng hiển thị vượt trội'},
    { id: 6,  name: 'Samsung Galaxy S23',price: 3000, describe: 'Smart Phone', category: 'Electronics', quantity: 1, image: Samsung1,description: ' 12GB 512GB tạo nên đột phá mạnh mẽ về mặt hiệu năng khi được trang bị vi xử lý Snapdragon 8 Gen 2 vượt trội cùng 12GB bộ nhớ RAM. Chất lượng hiển thị siêu sắc nét trên S23 Ultra tới từ tầm nền Dynamic AMOLED 2X 120Hz thế hệ mới. Bên cạnh đó, smartphone này còn sở hữu cụm camera cao cấp với độ rõ nét đạt tới 200MP. Viên pin 5000mAh cùng sạc nhanh 45W giúp nâng cao thời lượng sử dụng lên một tầm cao mới'},
    { id: 7,  name: 'Samsung Galaxy S24+',price: 3000, describe: 'Smart Phone', category: 'Clothing', quantity: 1, image: Samsung3,description:' 12GB 512GB được trang màn hình QHD+ Dynamic AMOLED 2X 6,8 inch với độ phân giải (3120 x 1440) và tốc độ làm mới 120Hz. Bên cạnh đó là chip Snapdragon 8 Gen 3 for Galaxy và RAM 12GB siêu ấn tượng. Đặc biệt, cụm camera sau với 4 camera có cảm biến chính 200MP, camera tele 50MP/10MP, camera góc siêu rộng 12MP cùng camera selfie 12MP,... Tất cả sẽ giúp bạn có những trải nghiệm ấn tượng, cực chất trên siêu phẩm này.' },
    { id: 8,  name:  'Galaxy Z Flip 5',price: 3000, describe: 'Smart Phone', category: 'Accessories', quantity: 1, image: Samsung4,description:' 5 có màn chính hình rộng 6.7 inch, với độ phân giải Full HD+ (1080 x 2636 Pixels), cụm camera trước 10MP và camera sau 12MP, rõ đến từng chi tiết. Cấu hình của sản phẩm mạnh mẽ nhờ hệ điều hành Android 10, con chipset mạnh mẽ Snapdragon 8 gen 2, với chip đồ họa tạo hình ảnh hiển thị hàng triệu màu sắc khác nhau. Sản phẩm có RAM 8GB, bộ nhớ trong 512GB.' },
    { id: 9,  name: 'Màn hình LG UltraGear', price: 2500, describe: 'Màn hình', category: 'Electronics', image: Maytinh1, quantity: 1, description: 'Samsung Galaxy Z Flip 5 có thiết kế màn hình rộng 6.7 inch và độ phân giải Full HD+ (1080 x 2640 Pixels), dung lượng RAM 8GB, bộ nhớ trong 256GB. Màn hình Dynamic AMOLED 2X của điện thoại này hiển thị rõ nét và sắc nét, mang đến trải nghiệm ấn tượng khi sử dụng.' },
    { id: 10, name: 'Màn hình Monitor Xiaomi', price: 3200,describe: 'Màn hình', category: 'Electronics', image: Maytinh2, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 11, name: 'Màn hình LG UltraWide',price: 2000, describe: 'Màn hình', category: 'Electronics', image: Maytinh3, quantity: 1,description:'Màn hình gaming LG ULTRAGEAR 24GS50F-B 24 inch sở hữu màn hình FHD cùng tần số làm mới 180Hz, tốc độ phản hồi 1ms MBR ấn tượng. Màn hình với công nghệ AMD FreeSync hỗ trợ mang lại trải nghiệm hình ảnh mượt mà. Cùng với đó màn hình còn sở hữu công nghệ tối ưu chơi game như chế độ ổn định màu đen, bộ đếm FPS hay đồng bộ hành động.' },
    { id: 12, name: 'Màn hình Samsung Odyssey',price: 3500, describe: 'Màn hình', category: 'Electronics', image: Maytinh4, quantity: 1,description:'Màn hình gaming LG ULTRAGEAR 24GS50F-B 24 inch sở hữu màn hình FHD cùng tần số làm mới 180Hz, tốc độ phản hồi 1ms MBR ấn tượng. Màn hình với công nghệ AMD FreeSync hỗ trợ mang lại trải nghiệm hình ảnh mượt mà. Cùng với đó màn hình còn sở hữu công nghệ tối ưu chơi game như chế độ ổn định màu đen, bộ đếm FPS hay đồng bộ hành động.' },
    { id: 13, name: 'Màn hình MSI Pro MP245V',price: 2299, describe: 'Màn hình', category: 'Electronics', image: Maytinh5 , quantity: 1,description:'Màn hình gaming LG ULTRAGEAR 24GS50F-B 24 inch sở hữu màn hình FHD cùng tần số làm mới 180Hz, tốc độ phản hồi 1ms MBR ấn tượng. Màn hình với công nghệ AMD FreeSync hỗ trợ mang lại trải nghiệm hình ảnh mượt mà. Cùng với đó màn hình còn sở hữu công nghệ tối ưu chơi game như chế độ ổn định màu đen, bộ đếm FPS hay đồng bộ hành động.'},
    { id: 14, name: 'Màn hình Xiaomi Monitor',price: 1900, describe: 'Màn hình', category: 'Electronics', image: Maytinh6 , quantity: 1,description:'Màn hình gaming LG ULTRAGEAR 24GS50F-B 24 inch sở hữu màn hình FHD cùng tần số làm mới 180Hz, tốc độ phản hồi 1ms MBR ấn tượng. Màn hình với công nghệ AMD FreeSync hỗ trợ mang lại trải nghiệm hình ảnh mượt mà. Cùng với đó màn hình còn sở hữu công nghệ tối ưu chơi game như chế độ ổn định màu đen, bộ đếm FPS hay đồng bộ hành động.'},
    { id: 15, name: 'Màn hình E-Dra',price: 2900, describe: 'Màn hình', category: 'Electronics', image: Maytinh7, quantity: 1 ,description:'Màn hình gaming LG ULTRAGEAR 24GS50F-B 24 inch sở hữu màn hình FHD cùng tần số làm mới 180Hz, tốc độ phản hồi 1ms MBR ấn tượng. Màn hình với công nghệ AMD FreeSync hỗ trợ mang lại trải nghiệm hình ảnh mượt mà. Cùng với đó màn hình còn sở hữu công nghệ tối ưu chơi game như chế độ ổn định màu đen, bộ đếm FPS hay đồng bộ hành động.'},
    { id: 16, name:  'Màn hình Viewsonic',price: 9999, describe: 'Màn hình', category: 'Electronics', image: Maytinh8, quantity: 1 ,description:'Màn hình gaming LG ULTRAGEAR 24GS50F-B 24 inch sở hữu màn hình FHD cùng tần số làm mới 180Hz, tốc độ phản hồi 1ms MBR ấn tượng. Màn hình với công nghệ AMD FreeSync hỗ trợ mang lại trải nghiệm hình ảnh mượt mà. Cùng với đó màn hình còn sở hữu công nghệ tối ưu chơi game như chế độ ổn định màu đen, bộ đếm FPS hay đồng bộ hành động.'},
    { id: 17, name: 'Wireless HUAWEI FreeClip', price: 2500, describe: 'Tai nghe Bluetooth', category: 'Headphone', image: Tainghe1, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 18, name: 'Wireless Baseus Bowie E11', price: 3200,describe: 'Tai nghe Bluetooth', category: 'Headphone', image: Tainghe2, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 19, name: 'Wireless Buds2 Pro',price: 2000, describe: 'Tai nghe Bluetooth', category: 'Headphone', image: Tainghe3, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 20, name: 'tai Sony WH-1000XM5',price: 3500, describe: 'Tai nghe Bluetooth', category: 'Headphone', image: Tainghe4, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 21, name: 'TAirPods 4 chống ồn',price: 2299, describe: 'Tai nghe Bluetooth', category: 'Headphone', image:  Tainghe5, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 22, name: 'Wireless Anker Soundcore R50i ',price: 1900, describe: 'Tai nghe Bluetooth', category: 'Headphone', image:  Tainghe6, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 23, name: 'TAirPods Pro 2 2023 USB-C ',price: 2900, describe: 'Tai nghe Bluetooth', category: 'Headphone', image: Tainghe7, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 24, name: 'Wireless Baseus Bowie E11',price: 9999, describe: 'Tai nghe Bluetooth', category: 'Headphone', image: Tainghe8, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 25, name: 'Đồng hồ Huawei Watch GT 5', price: 2500, originalPrice: 3000, describe: 'Smart Watch', category: 'Smart Watch', image: Watch1, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 26, name: 'Đồng hồ Huawei Watch D2', price: 3200, originalPrice: 4000, describe: 'Smart Watch', category: 'Smart Watch', image: Watch2, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 27, name: 'Apple Watch SE 2 ', price: 2000, originalPrice: 2500, describe: 'Smart Watch', category: 'Smart Watch', image: Watch3, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 28, name: 'Màn hình Samsung Odyssey', price: 3500, originalPrice: 4500, describe: 'Smart Phone', category: 'Smart Watch', image: Watch4, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 29, name: 'Màn hình MSI Pro MP245V', price: 2299, originalPrice: 2800, describe: 'Smart Phone', category: 'Smart Watch', image: Watch5, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 30, name: 'Màn hình Xiaomi Monitor', price: 1900, originalPrice: 2400, describe: 'Smart Phone', category: 'Smart Watch', image: Watch6, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 31, name: 'Màn hình E-Dra', price: 2900, originalPrice: 3400, describe: 'Smart Phone', category: 'Smart Watch', image: Watch7, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 32, name: 'Màn hình Viewsonic', price: 9999, originalPrice: 12000, describe: 'Smart Phone', category: 'Smart Watch', image: Watch8, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 34, name: 'Samsung Galaxy Tab S9 FE', price: 1100, describe: 'Smart Phone', image: sale1, sale: '20%',description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 35, name: 'Máy Tính Bảng Lenovo Tab M9', price: 2100, describe: 'Smart Phone', image: sale2, sale: '25%',description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 36, name: 'OPPO Reno10 Pro+ 5G 12GB ', price: 1700, describe: 'Monitor', image: sale3, sale: '18%' ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 37, name: 'Samsung Galaxy S23 FE 5G', price: 1700, describe: 'Monitor', image: sale4, sale: '18%',description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 38, name: 'Xiaomi Redmi Pad SE ', price: 1700, describe: 'Monitor', image: sale5, sale: '18%' ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 39, name: 'TECNO SPARK 30C 4GB 128GB', price: 1700, describe: 'Monitor', image: sale6, sale: '18%',description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 40, name: 'Samsung Galaxy A05S 4GB 128GB', price: 1700, describe: 'Monitor', image: sale7, sale: '18%' ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 49, name: 'iPad Gen 10 10.9 ', price: 2500, originalPrice: 3000, describe: 'Ipad', category: 'Ipad', image: Ipad1, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 41, name: 'Laptop ASUS VivobookW', price: 2500, describe: 'Laptop', category: 'Laptop', image: Laptop1, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 42, name: 'Laptop ASUS Gaming VivoBook ', price: 3200,describe: 'Laptop', category: 'Laptop', image: Laptop2, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 43, name: 'Laptop ASUS TUF Gaming ',price: 2000, describe: 'Laptop', category: 'Laptop', image: Laptop3, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 44, name: 'Laptop ASUS VivoBook Go ',price: 3500, describe: 'Laptop', category: 'Laptop', image: Laptop4, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 45, name: 'Laptop ASUS Gaming',price: 2299, describe: 'Laptop', category: 'Laptop', image:  Laptop5, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 46, name: 'Laptop ASUS Zenbook',price: 1900, describe: 'Laptop', category: 'Laptop', image: Laptop6, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 47, name: 'Laptop ASUS Vivobook',price: 2900, describe: 'Laptop', category: 'Laptop', image: Laptop7, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 48, name: 'Laptop ASUS TUF Gaming A15 ',price: 9999, describe: 'Laptop', category: 'Laptop', image: Laptop8, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 50, name: 'iPad mini 7 2024 ', price: 3200, originalPrice: 4000, describe: 'Ipad', category: 'Ipad', image: Ipad2, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 51, name: 'iPad Air 6 M2 11 ', price: 2000, originalPrice: 2500, describe: 'Ipad', category: 'Ipad', image: Ipad3, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 52, name: 'iPad mini 6 WiFi ', price: 3500, originalPrice: 4500, describe: 'Ipad', category: 'Ipad', image: Ipad4, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 53, name: 'iPad 10.2 2021 WiFi ', price: 2299, originalPrice: 2800, describe: 'Ipad', category: 'Ipad', image: Ipad5, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 54, name: 'iPad Pro M4 11 inch Wifi ', price: 1900, originalPrice: 2400, describe: 'Ipad', category: 'Ipad', image: Ipad6, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 55, name: 'iPad Gen 10 10.9 inch 2022', price: 2900, originalPrice: 3400, describe: 'Ipad', category: 'Ipad', image: Ipad7, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 56, name: 'iPad Air 6 M2 11 inch Wifi ', price: 9999, originalPrice: 12000, describe: 'Ipad', category: 'Ipad', image: Ipad8, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 60, name: 'Chuột Có dây Silent Rapoo ', price: 2500, originalPrice: 3000, describe: 'Mouse', category: 'Mouse', image: Mouse1, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 61, name: 'Chuột DareU LM106G', price: 3200, originalPrice: 4000, describe: 'Mouse', category: 'Mouse', image: Mouse2, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 62, name: 'Chuột Logitech M170', price: 2000, originalPrice: 2500, describe: 'Mouse', category: 'Mouse', image: Mouse3, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 63, name: 'Chuột Silent Logitech M240', price: 3500, originalPrice: 4500, describe: 'Mouse', category: 'Mouse', image: Mouse4, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 64, name: 'Chuột Zadez M213', price: 2299, originalPrice: 2800, describe: 'Mouse', category: 'Mouse', image: Mouse5, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 65, name: 'Chuột Logitech M185', price: 1900, originalPrice: 2400, describe: 'Mouse', category: 'Mouse', image: Mouse6, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
    { id: 66, name: 'Chuột Logitech G102 Lightsync', price: 2900, originalPrice: 3400, describe: 'Mouse', category: 'Mouse', image: Mouse7, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 67, name: 'Chuột Gaming Rapoo V11s', price: 9999, originalPrice: 12000, describe: 'Mouse', category: 'Mouse', image: Mouse8, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
     { id: 60, name: 'Chuột Có dây Silent Rapoo ', price: 2500, originalPrice: 3000, describe: 'Mouse', category: 'Mouse', image: Mouse1, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 61, name: 'Chuột DareU LM106G', price: 3200, originalPrice: 4000, describe: 'Mouse', category: 'Mouse', image: Mouse2, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 62, name: 'Chuột Logitech M170', price: 2000, originalPrice: 2500, describe: 'Mouse', category: 'Mouse', image: Mouse3, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
  { id: 63, name: 'Chuột Silent Logitech M240', price: 3500, originalPrice: 4500, describe: 'Mouse', category: 'Mouse', image: Mouse4, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 64, name: 'Chuột Zadez M213', price: 2299, originalPrice: 2800, describe: 'Mouse', category: 'Mouse', image: Mouse5, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 65, name: 'Chuột Logitech M185', price: 1900, originalPrice: 2400, describe: 'Mouse', category: 'Mouse', image: Mouse6, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 66, name: 'Chuột Logitech G102 Lightsync', price: 2900, originalPrice: 3400, describe: 'Mouse', category: 'Mouse', image: Mouse7, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 67, name: 'Chuột Gaming Rapoo V11s', price: 9999, originalPrice: 12000, describe: 'Mouse', category: 'Mouse', image: Mouse8, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 72, name: 'Bàn Phím Rapoo V500alloy', price: 2500, describe: 'KeyBoard', category: 'KeyBoard', image: KeyBoard1, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 73, name: 'Bàn Phím Tournament Edition', price: 3200,describe: 'KeyBoard', category: 'KeyBoard', image: KeyBoard2, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 74, name: 'Bàn Phím Asus TUF K1',price: 2000, describe: 'KeyBoard', category: 'KeyBoard', image: KeyBoard3, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 75, name: 'Bàn Phím Rapoo V50S',price: 3500, describe: 'KeyBoard', category: 'KeyBoard', image: KeyBoard4, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 76, name: 'Bàn Phím Zadez G-850K',price: 2299, describe: 'KeyBoard', category: 'KeyBoard', image:  KeyBoard5, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 77, name: 'Bàn phím Asus DELUXE RD SW',price: 1900, describe: 'KeyBoard', category: 'KeyBoard', image: KeyBoard6, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 78, name: 'Bàn Phím V500 Pro Rainbow',price: 2900, describe: 'KeyBoard', category: 'KeyBoard', image: KeyBoard7, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  { id: 79, name: 'Bàn Phím K55 CORE RGB',price: 9999, describe: 'KeyBoard', category: 'KeyBoard', image: KeyBoard8, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},
  ];
  const space = [
    { id: 2,  name: 'Iphone 14',price: 3000, describe:'Smart Phone', image:Shirt,sale:'50%', quantity: 1,description: 'The Premium Round Neck Shirt from Craft Clothing is a testament to comfort and quality' },
    { id: 5,  name: 'Samsung Galaxy S24',price: 3000, describe: 'Smart Phone', category: 'Clothing',sale:'50%', quantity: 1, image: Shoes, description: ' phiên bản 512GB được trang bị con chip Exynos 2400 kết hợp cùng dung lượng RAM 12GB cho hiệu năng đáng kinh ngạc. Cụm camera với cảm biến chính 50MP đảm bảo mang tới những bức ảnh sống động và khả năng quay video Super HDR đỉnh cao. Màn hình Dynamic AMOLED 2X cùng độ phân giải Quad-HD+ với độ sáng 2.600 nit hỗ trợ mang lại khả năng hiển thị vượt trội'},
    { id: 9,  name: 'Màn hình LG UltraGear', price: 2500, describe: 'Màn hình', category: 'Electronics',sale:'50%', image: Maytinh1, quantity: 1, description: 'Samsung Galaxy Z Flip 5 có thiết kế màn hình rộng 6.7 inch và độ phân giải Full HD+ (1080 x 2640 Pixels), dung lượng RAM 8GB, bộ nhớ trong 256GB. Màn hình Dynamic AMOLED 2X của điện thoại này hiển thị rõ nét và sắc nét, mang đến trải nghiệm ấn tượng khi sử dụng.' },
    { id: 17, name: 'Wireless HUAWEI FreeClip', price: 2500, describe: 'Tai nghe Bluetooth', category: 'Headphone',sale:'50%', image: Tainghe1, quantity: 1,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.' },
    { id: 53, name: 'iPad 10.2 2021 WiFi ', price: 2299, originalPrice: 2800, describe: 'Ipad', category: 'Ipad',sale:'50%', image: Ipad5, quantity: 1 ,description: 'Màn hình Monitor Xiaomi 27 inch A27i ELA5345EU có độ phân giải Full HD (1920 x 1080) cùng tần số quét lên đến 100 Hz đem lại trải nghiệm hình ảnh mượt mà. Mẫu màn hình 27 inch sử dụng công nghệ tấm nền IPS cho màu sắc chân thực, góc nhìn rộng 178 độ, đáp ứng chuẩn màu sắc cao với 99% sRGB và độ sai lệch màu Delta E dưới 2, phù hợp cho công việc thiết kế đòi hỏi chất lượng cao. Các cổng kết nối HDMI 2.0 và DisplayPort giúp kết nối đa thiết bị dễ dàng và linh hoạt.'},

  ]

function ProductDetail({addToCart}) {
    const {id} = useParams();
    const product = products.find((p) => p.id === parseInt(id))
    const navigate = useNavigate();      
    const handleBackToHome = () => {
      navigate('/address')
      addToCart(product);
    }
    const handleAddToCart = () => {
      addToCart(product);
      navigate('/cart')
    }

  return (
    <>
    <div className="product-detail-container">
      <div className="product-detail">
        <div className="product-detail-image">
          <img src={product.image} alt={product.name}  />
        </div>
        <div className="product-detail-info">
          <h4 className="product-category">{product.describe.toUpperCase()}</h4>
          <h1 className="product-title11">{product.name}</h1>
          <div className="product-rating ">
            <span>4.1</span><i className="fa-solid fa-star" ></i>

          </div>
          <p className="product-price">${product.price}</p>
          <p className="product-description11">{product.description}</p>
          <div className="row">
          </div>
          <div className="product-detail-buttons">
            <button className="btn-add-to-cart" onClick={handleAddToCart}>Thêm giỏ hàng</button>
            <button className="btn-go-to-cart" onClick={handleBackToHome}>Mua ngay</button>
          </div>
        </div>
      </div>
    </div>
    <h3 style={{fontWeight:'700'}}>Các sản phẩm tương tự</h3>
    <div className="cacsanphamtuongtu">
      {space.map((product) => (
              <div className="product-card" key={product.id}>
                <Link to={`/products/${product.id}`} className="product-link">
                  <div className="product-image-container">
                    <img src={product.image} alt={product.name} className="product-image" />
                  </div>
                  <div className="discount-badge"><span>{product.sale}</span></div>
                  <h3 className="product-title">{product.name}</h3>
                  <p className="product-description">{product.describe}</p>
                  <div className="product-price-container">
                    <h4 className="current-price">{product.price} $</h4>
                    <h5 className="original-price">{product.price} $</h5>
                  </div>
                  <div className="rating-container">
                    <div className="icon-star" >
                      <i className="fa-solid fa-star"></i>
                      <i className="fa-solid fa-star"></i>
                      <i className="fa-solid fa-star"></i>
                      <i className="fa-solid fa-star"></i>
                      <i className="fa-solid fa-star-half-stroke"></i>
                    </div>
                    <span className="review-count">(99)</span>
                  </div>
                </Link>
            </div>
            ))
          }
    </div>
    <hr />
    <Footer/>
    </>
  )
  
}

export default ProductDetail
